### PR TITLE
Prevent chicken from overwriting cJSON.c on Windows.

### PR DESCRIPTION
**Pull request by elderica**

### CODE REVIEW

**Comment by elderica** [comment]
I tried to build this on MSYS2(Windows x86).
When building cjson.scm, chicken generates cjson.c. This means chicken overwrites original cJSON.c.
So, I moved them to separate directory.

**Comment by kristianlm** [comment]
Hi @sbwhitecap!

I really appreciate your PR and your commit looks good. However, I feel the commit message itself is a little brief. Could you insert your explanation from this PR and put it into the commit? If you amend your commit and do a forced-push, then it'll be just to click "merge" for me.

Thanks for trying to improve chicken-cjson!

**Comment by elderica** [comment]
Thank you for reviewing my PR. I fixed commit message.

**Comment by kristianlm** [comment]
Great, thanks for the improvement!

And btw, I'm quite curious as to what you're using `chicken-cjson` for!

**Pull request merged**
